import { StyleSheet } from "react-native";
import { colors } from "@/styles/shared/colors/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.neutral.white,
  },
  headerSection: {
    position: "relative",
    paddingHorizontal: 24,
    paddingBottom: 48,
    paddingTop: 24,
  },
  background: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "100%",
  },
  backgroundSvg: {
    width: "100%",
  },
  content: {
    flex: 1,
    backgroundColor: colors.neutral.white,
    paddingHorizontal: 24,
    paddingTop: 32,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    marginTop: -32,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  greeting: {
    color: colors.neutral.white,
  },
  userName: {
    color: colors.neutral.white,
  },
  profilePicture: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.neutral.gray3,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.neutral.white,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 8,
    shadowColor: colors.neutral.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  searchIcon: {
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: colors.neutral.black,
  },
  sectionTitle: {
    marginVertical: 24,
    color: colors.neutral.black,
  },
  serviceOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 32,
    paddingHorizontal: 8,
  },
  serviceOption: {
    width: 72,
  },
  serviceIconContainer: {
    width: 72,
    height: 72,
    borderRadius: 16,
    backgroundColor: colors.primary.light.default,
    justifyContent: "center",
    alignItems: "center",
  },
  serviceLabel: {
    fontSize: 12,
    color: colors.neutral.gray1,
    textAlign: "center",
    marginTop: 8,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.neutral.white,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutral.gray4,
    gap: 12,
  },
  searchInputContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.neutral.gray4,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
  },
  modalSearchInput: {
    flex: 1,
    height: 40,
    fontSize: 16,
    color: colors.neutral.black,
  },
  closeButton: {
    paddingVertical: 8,
  },
  searchResults: {
    flex: 1,
    padding: 16,
  },
  searchResultCard: {
    backgroundColor: colors.neutral.white,
    borderRadius: 12,
    marginBottom: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.neutral.gray4,
  },
  searchResultRoute: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  searchResultCity: {
    color: colors.neutral.black,
    fontWeight: '600',
    flex: 0,
    minWidth: '40%',
  },
  searchResultInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  searchResultDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  searchResultText: {
    color: colors.neutral.gray1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 32,
  },
  noResults: {
    textAlign: 'center',
    color: colors.neutral.gray2,
    marginTop: 32,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.neutral.white,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
    width: "100%",
  },
  searchPlaceholder: {
    color: colors.neutral.gray2,
    flex: 1,
  },
  rideCard: {
    backgroundColor: colors.neutral.white,
    borderRadius: 12,
    marginBottom: 16,
    overflow: 'hidden',
    shadowColor: colors.neutral.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  rideInfo: {
    flex: 1,
  },
  rideHeader: {
    backgroundColor: colors.primary.light.default,
    padding: 16,
    marginBottom: 0,
  },
  rideRoute: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  rideContent: {
    padding: 16,
  },
  rideDriver: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  driverPhoto: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.neutral.gray4,
  },
  driverName: {
    color: colors.neutral.black,
    fontWeight: '500',
  },
  rideDetails: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: colors.neutral.gray4,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.primary.light.default,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailText: {
    color: colors.neutral.black,
    fontWeight: '500',
  },
  driverSection: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.neutral.white,
    borderRadius: 12,
    padding: 16,
    gap: 12,
    borderWidth: 1,
    borderColor: colors.neutral.gray4,
  },
  driverInfo: {
    flex: 1,
  },
  driverPicture: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  messageButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: colors.primary.light.default,
  },
  rideInfoSection: {
    flex: 1,
  },
  routeInfo: {
    marginBottom: 24,
  },
  locationItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    gap: 12,
  },
  locationText: {
    flex: 1,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  rideDetailsContainer: {
    backgroundColor: colors.neutral.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    height: '90%',
    marginTop: 'auto',
  },
  map: {
    width: '100%',
    height: 200,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    padding: 8,
  },
  paymentSection: {
    marginTop: 24,
    padding: 16,
    backgroundColor: colors.neutral.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.neutral.gray4,
  },
  paymentMethod: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  bottomActions: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: colors.neutral.gray4,
    backgroundColor: colors.neutral.white,
  },
  payButton: {
    backgroundColor: colors.primary.normal.default,
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  ridesContainer: {
    paddingHorizontal: 4,
  },
  noRidesText: {
    textAlign: 'center',
    color: colors.neutral.gray2,
    marginTop: 32,
  },
  loadingMore: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  seeMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 8,
    paddingVertical: 12,
    marginTop: -4,
    paddingHorizontal: 4,
  },
  reserveButton: {
    backgroundColor: colors.primary.normal.default,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 16,
    alignItems: 'center',
  },
  reserveButtonText: {
    color: colors.neutral.white,
    fontWeight: '600',
  },
}); 